services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es-wild-project
    ports:
      - 9200:9200
    environment:
#      - ELASTIC_PASSWORD_FILE=/run/secrets/es-password
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1
      - xpack.security.enabled=false    # Avoid using https certs
    volumes:
      - es-data:/usr/share/elasticsearch/data
#    secrets:
#      - es-password
    networks:
      - twps
#    network_mode: "host"
    restart: unless-stopped

  frontend:
    build: ./Web
    image: leosfsm/wps-frontend
    container_name: frontend-wild-project
    ports:
      - 8080:80
#    networks:
#     - twps
#    network_mode: "host"
    restart: unless-stopped

  backend:
    build: ./Backend
    image: leosfsm/wps-backend
    container_name: backend-wild-project
    ports:
      - 5000:5000
    environment:
      - ELASTIC_IP=es-wild-project
      - ELASTIC_PORT=9200
#    volumes:
#      - es-config:/srv/wps-backend/es-config
#    secrets:
#      - es-password
    networks:
      - twps
#    network_mode: "host"
    restart: unless-stopped

networks:
  twps:
    name: twps

volumes:
  es-data:

#secrets:
#  es-password:
#    file: ./es-password
